#!/bin/sh

# This script calls ./c5.py with the configuration defined here.
# Run ./c5.py to display explanation of variables

export C5_HOST="127.0.0.1"
export C5_IP="127.0.0.1"
export C5_ROOT="root"
export C5_LOGIN="your.login"
export C5_HTTP="4301"
export C5_SOCK="4302"
export C5_MAIL="your.mail@your.domain"
export C5_CERT="SS"
export C5_URL="$C5_HOST:4301"
export C5_WEBSOCKET="$C5_HOST:4302"
export C5_REDIRECT=''
export C5_VALIDATE=''
export C5_LOCAL="1"
export C5_USERS_URL="http://127.0.0.1:8081/users/internal/c5/profiles"
export C5_USERS_TOKEN_FILE="/etc/c5/secrets/users-token"
export C5_EXECUTION_ENABLED="0"
export C5_CUSTOMIZE="local_my.py"

./c5.py $@
