#!/bin/sh
# Argument 1 : the python file to compile WITHOUT .py EXTENSION

PY=$1.py
JS=$1.js
JSON=$1.json
TMP_SOURCE=$(mktemp "${TMPDIR:-/tmp}/c5-py2js.XXXXXX") || exit 1
C5_SOURCE_DIR=$(dirname "$(readlink -f "$0")") || exit 1

cleanup() {
    rm -f "$TMP_SOURCE"
}
trap cleanup EXIT HUP INT TERM

if [ -e $JS ]
then
    mv $JS $JS~
fi
if [ -e $JSON ]
then
    mv $JSON $JSON~
fi

restore() {
    if [ -e $JS~ ]
    then
        mv $JS~ $JS
    fi
    if [ -e $JSON~ ]
    then
        mv $JSON~ $JSON
    fi
    # rm $PY.xxx
}

BEFORE=''
case $1 in
	COMPILE*)
		COMPILER=$(echo $1 | sed -e 's,/.*,,' | tr '[A-Z]' '[a-z]')
		FILES="$PY"
		SESSION=$(
			echo
			echo 'if not Compile.worker: eval("new Session([' \
				 $(grep -E '^class Q[A-Za-z0-9_]+\(' $PY |
                  tr '\n' '%' |
                  sed -r -e 's/%*class *([^%( ]*)\([^%]*/new \1(),/g' -e 's/,%$//'
                 ) '])")'
			)
		[ -d $1 ] && chmod 700 $1
        BEFORE="importScripts('JS/$COMPILER.js' + location.search)"
		;;
	compile_*)
		COMPILER=
		FILES="$C5_SOURCE_DIR/compatibility.py $C5_SOURCE_DIR/xxx_local.py $C5_SOURCE_DIR/options.py $C5_SOURCE_DIR/compile.py $C5_SOURCE_DIR/pedagogy.py $C5_SOURCE_DIR/question.py $PY"
		JS=JS/$JS
		;;
    bare_*)
		COMPILER=
		FILES="$PY"
		JS=JS/$JS
		;;
	*)
		COMPILER=
		FILES="$C5_SOURCE_DIR/compatibility.py $C5_SOURCE_DIR/xxx_local.py $C5_SOURCE_DIR/options.py $PY"
		JS=JS/$JS
		;;
esac

echo "$BEFORE" >"$TMP_SOURCE"
if cat $FILES >>"$TMP_SOURCE"
then
    :
else
    restore
    exit 1
fi

echo "$SESSION" >>"$TMP_SOURCE"

if nodejs "$C5_SOURCE_DIR/RapydScript/bin/rapydscript" --prettify --bare "$TMP_SOURCE" >$JS
then
    echo "$PY → $JS OK"
    if [ "$COMPILER" != "" ]
        then
        "$C5_SOURCE_DIR/rewrite.py" $JS
        fi
else
    echo "$PY → $JS FAIL"
    restore
    exit 1
fi

if [ "$COMPILER" != "" ]
then
	if cat "$C5_SOURCE_DIR/options.py" "$C5_SOURCE_DIR/compile.py" \
		"$C5_SOURCE_DIR/$COMPILER.py" "$C5_SOURCE_DIR/pedagogy.py" \
		"$C5_SOURCE_DIR/question_before.py" "$PY" \
		"$C5_SOURCE_DIR/question_after.py" |
		(cd $(dirname $JS) ; python3) >$JSON
    then
        echo "$PY → $JSON OK"
    else
        echo "$PY → $JSON FAIL"
        restore
        exit 1
    fi
fi
